sudo: required

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer install --no-scripts

script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_success:
  - ./vendor/bin/test-reporter  
