name: GitHub Actions
on: [push]
env:
  APP_IMAGE: keboola/gelf-server
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Print Docker version
        run: |
          docker -v
      - name: Build image and run tests
        run: |
          docker-compose build --pull
          docker-compose run --rm tests
